# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Falmarri
tagline:          'The Blog'
description:      'My testing website/blog.'
url:              http://www.falmarri.com

author:
  name:           'David Knapp'
  url:            

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/Falmarri
